Controllers/BillController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProductGallary.Constants;
using ProductGallary.Models;
using ProductGallary.Reposatories;
using ProductGallary.TDO;

namespace ProductGallary.Controllers
{
    public class BillController:Controller
    {
        private readonly IReposatory<Order> ordersReposatory;
        private readonly IReposatory<Bill> billsReposatory;
        private readonly UserManager<ApplicationUser> userManger;
        private readonly CartInterface cartReposatory;

        public BillController(IReposatory<Order> _ordersReposatory, IReposatory<Bill> _billsReposatory, UserManager<ApplicationUser> _userManger, CartInterface _cartReposatory)
        {
            this.ordersReposatory=_ordersReposatory;
            this.billsReposatory = _billsReposatory;
            this.userManger = _userManger;
            cartReposatory = _cartReposatory;
        }

        [Authorize(Roles =$"{Roles.CUSTOMER_ROLE}")]
        [HttpGet]
        // this action used to Display Bill
        public async Task<IActionResult> DisplayBill()
        {
            if(TempData.ContainsKey(Constant.ORDERID))
            {
                Guid billId = (Guid)TempData[Constant.ORDERID];
                Order order = this.ordersReposatory.GetById(billId);
                ApplicationUser user = await userManger.GetUserAsync(this.HttpContext.User);
                BillInfoDTO billInfoDTO = new BillInfoDTO
                {
                    Id = billId,
                    currentDate = DateTime.Now.Date.ToString(),
                    currentTime = DateTime.Now.TimeOfDay.ToString(),
                    userName = user.Name,
                    products = new List<ProductInfoDTO>()
                    
                };
                Cart cart = cartReposatory.GetById(order.Cart_Id);
                foreach (Product pro in order.Cart.products)
                {
                    ProductInfoDTO productInfo = new ProductInfoDTO
                    {
                        Id=pro.Id,
                        Name=pro.Name,
                        Image=pro.Image, 
                        Price= ((bool)pro.HasDiscount)? (pro.Price) - ((pro.DiscountPercentage / 100) * (pro.Price)):pro.Price
                    };
                    billInfoDTO.Price += (float)(pro.Price==null?0:pro.Price);
                    billInfoDTO.products.Add(productInfo);
                }
                // save Bill In database
                this.billsReposatory.Insert(new Bill { OrderId = billId,Price=billInfoDTO.Price});
                return View("DisplayBill", billInfoDTO);

            }
            return RedirectToAction("Index","Home");
        }

        [Authorize(Roles = $"{Roles.ADMIN_ROLE}")]
        [HttpGet]
        public IActionResult DisplayAllBills()
        {
            List<BillInfoDTO> billsInfoDTO = new List<BillInfoDTO>();
            List<Bill> Bills = this.billsReposatory.GetAll();

            foreach (var item in Bills)
            {

                Order order = this.ordersReposatory.GetById((Guid)item.OrderId);
                BillInfoDTO billInfoDTO = new BillInfoDTO
                {
                    userName = order==null?"غير معروف":order.User.Name,
                    Id = item.Id,
                    Price = item.Price,
                    products = new List<ProductInfoDTO>()
                };
                Cart cart = this.cartReposatory.GetById(order.Cart_Id);
                if (cart != null) { 
                foreach (Product pro in order.Cart.products)
                {
                    billInfoDTO.products.Add(
                        new ProductInfoDTO
                        {
                            Name=pro.Name,
                            Price = pro.HasDiscount==null?pro.Price:(bool)pro.HasDiscount ? (pro.Price) - ((pro.DiscountPercentage / 100) * (pro.Price)) : pro.Price
                        }
                        );
                }}
                billsInfoDTO.Add(billInfoDTO);
            }


            return View(billsInfoDTO);
        }
    }
}

Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProductGallary.Constants;
using ProductGallary.Models;
using ProductGallary.Reposatories;
using ProductGallary.TDO;

namespace ProductGallary.Controllers
{
    public class CartController : Controller
    {
        private readonly UserManager<ApplicationUser> userManger;

        CartInterface cartrepo;
        IReposatory<Product> reposatory;
        IFilter<Cart> filter;
        public CartController(CartInterface cartrepo, UserManager<ApplicationUser> userManger, IReposatory<Product> reposatory, IFilter<Cart> filter)
        {
            this.cartrepo = cartrepo;
            this.userManger = userManger;
            this.reposatory = reposatory;
            this.filter = filter;
        }
        public IActionResult Index()
        {
           
            UserDto infoDTO = new UserDto();
            var userID = userManger.GetUserId(HttpContext.User);
            infoDTO.user_id = userID;
            return RedirectToAction("shoppingcart",infoDTO);
        }

        [Authorize(Roles = $"{Roles.CUSTOMER_ROLE}")]


        public IActionResult shoppingcart(string user_id)
        {
            List<Guid> productsIds = getProductsIds();
            //var cart = filter.filter(user_id);
            List<ProductInfoDTO> cartProducts = new List<ProductInfoDTO>();
            foreach(Guid id in productsIds)
            {
                Product product = this.reposatory.GetById(id);
                if(product!=null)
                {
                    cartProducts.Add(
                    new ProductInfoDTO
                    {
                        Id = product.Id,
                        Name=product.Name,
                        Image=product.Image,
                        Price=product.DiscountPercentage != null?(product.Price) - ((product.DiscountPercentage / 100) * (product.Price)) :product.Price,
                        DiscountPercentage=product.DiscountPercentage==null?0: product.DiscountPercentage
                    }
                    );
                }
            }
            return View(cartProducts);
        }
       [HttpPost]
       [Authorize(Roles = $"{Roles.CUSTOMER_ROLE}")]
        public IActionResult addtocart([FromRoute]Guid id)
        {
            var userID = userManger.GetUserId(HttpContext.User);
            if (userID!=null)
            {
                //Cart cart = new Cart();
                //var p = reposatory.GetById(id);
                if (ModelState.IsValid)
                {
                    List<Guid> products;
                    if (!TempData.ContainsKey(Constant.PRODUCTS))
                    {
                        products = new List<Guid>()
                        {
                            id
                        };
                        
                    }
                    else
                    {

                        products =JsonConvert.DeserializeObject<List<Guid>>(TempData[Constant.PRODUCTS].ToString());
                        products.Add(id);
                        


                    }
                    // save Products Ids In Session
                    TempData[Constant.PRODUCTS] = JsonConvert.SerializeObject(products);
                 
                    return RedirectToAction("index");
                }
                return Redirect("Details");
            }
            else
            {
                return RedirectToAction("Login");
            }
        }
        [Authorize(Roles = $"{Roles.CUSTOMER_ROLE}")]
        public IActionResult RemoveFromCart(Guid id)
        {
            List<Guid> productsIds = getProductsIds();
            productsIds.Remove(id);
            // update cart
            TempData[Constant.PRODUCTS] = JsonConvert.SerializeObject(productsIds);
            return RedirectToAction("shoppingcart");
        }

        [Authorize(Roles = $"{Roles.CUSTOMER_ROLE}")]
        public IActionResult ClearCart()
        {
            TempData.Remove(Constant.PRODUCTS);
            return RedirectToAction("shoppingcart");
        }

        // this method used to get all Products Ids From Session
        private List<Guid> getProductsIds()
        {
            List<Guid> productsIds = new List<Guid>();
            if (TempData.ContainsKey(Constant.PRODUCTS))
            {
                productsIds = JsonConvert.DeserializeObject<List<Guid>>(TempData[Constant.PRODUCTS].ToString());
                TempData.Keep();
            }
            return productsIds;
        }

    }
}

Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using ProductGallary.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using ProductGallary.Reposatories;
using ProductGallary.TDO;
using Microsoft.AspNetCore.Authorization;
using ProductGallary.Constants;

namespace ProductGallary.Controllers
{
    public class CategoryController : Controller
    {
        IReposatory<Category> CategRepo;
        private readonly UserManager<ApplicationUser> userManger;
        //  CategoryRepository courseRepository;
        public CategoryController(IReposatory<Category> _CategRepo , UserManager<ApplicationUser> f)
        {
            CategRepo = _CategRepo;
            userManger = f;
        }
        public IActionResult Index()
        {

            var Cat = CategRepo.GetAll();

            return View(Cat);
        }
        [Authorize(Roles = $"{Roles.ADMIN_ROLE}")]
        public IActionResult New()
        {
            return View(new Category());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = $"{Roles.ADMIN_ROLE}")]
        public IActionResult Savenew(Category newCateg)

        {
             var userID= userManger.GetUserId(HttpContext.User);

            if (ModelState.IsValid == true)
            {
                newCateg.User_Id = userID;
                //save
                CategRepo.Insert(newCateg);
                return RedirectToAction("Index");
            }
            else
            {
                return View("New", newCateg);
            }
        }
        [Authorize(Roles = $"{Roles.ADMIN_ROLE}")]
        public IActionResult Update(Guid id)
        {
            //ViewData["GallaryList"] = ProductRepo.GetAll();
            var oldcateg = CategRepo.GetById(id);
            return View(oldcateg);
        }
        [Authorize(Roles = $"{Roles.ADMIN_ROLE}")]
        public IActionResult Saveupdate(Guid id, Category newcat)
        {
            ViewData["CategList"] = CategRepo.GetAll();
            if (ModelState.IsValid)
            {
                CategRepo.Update(id, newcat);
                return RedirectToAction("Index");
            }
            return View("Edit", newcat);
        }
        [Authorize(Roles = $"{Roles.ADMIN_ROLE}")]
        public IActionResult Delete(Guid id)
        {
            CategRepo.Delete(id);
            return RedirectToAction("Index");
        }


        // details of category 

        public IActionResult Details(Guid id)
        {
            Category gal = CategRepo.GetById(id);
            return View(gal);
        }

    }
}

Controllers/GallaryController.cs
using Microsoft.AspNetCore.Mvc;
using ProductGallary.Models;
using ProductGallary.TDO;
using ProductGallary.Constants;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using ProductGallary.Reposatories;

namespace ProductGallary.Controllers
{
    public class GallaryController : Controller
    {
        IWebHostEnvironment env;
        private readonly UserManager<ApplicationUser> userManger;
        IReposatory<Gallary> reposatory;
        IFilter<Gallary> filter;
        public GallaryController(IReposatory<Gallary> reposatory, IWebHostEnvironment env, UserManager<ApplicationUser> userManger, IFilter<Gallary> filter)
        {
            this.reposatory = reposatory;
            this.env = env;
            this.userManger = userManger;
            this.filter = filter;
        }

        List<GalaryInfoDTO> galaryInfos = new List<GalaryInfoDTO>();
        public IActionResult Index()
        {
            var gallary = reposatory.GetAll();
            List<GalaryInfoDTO> galaryInfos = new List<GalaryInfoDTO>();
            foreach (var item in gallary)
            {
                GalaryInfoDTO dto = new GalaryInfoDTO();
                dto.Id = item.Id;
                dto.Name = item.Name;
                dto.Logo = item.Logo;
                dto.Created_Date = item.Created_Date;
                var userID = userManger.GetUserId(HttpContext.User);
                dto.user_id = userID;
                galaryInfos.Add(dto);
            }
            return View(galaryInfos);
        }
        public IActionResult Details(Guid id)
        {
            Gallary gal = reposatory.GetById(id);
            return View(gal);
        }
        [Authorize(Roles = $"{Roles.BUYER_ROLE}")]
        public IActionResult DetailsforBuyer(Guid id)
        {
            Gallary gal = reposatory.GetById(id);
            return View(gal);
        }
        [Authorize(Roles = $"{Roles.BUYER_ROLE}")]
        public IActionResult inseart()
        {
            return View( );
        }
        


        [HttpPost]
        [Authorize(Roles = $"{Roles.BUYER_ROLE}")]
        public IActionResult savegallary(GalaryCreateDTO galaryCreate)
        {

            if (ModelState.IsValid)
            {

                Gallary gallary = new Gallary();

                //upload fole to server

                string uploadimg = Path.Combine(env.WebRootPath, "img/GallaryLogo");
                string uniqe = Guid.NewGuid().ToString() + "_" + galaryCreate.Logo.FileName;
                string pathfile = Path.Combine(uploadimg, uniqe);
                using (var filestream = new FileStream(pathfile, FileMode.Create))
                {
                    galaryCreate.Logo.CopyTo(filestream);
                    filestream.Close();
                }
                
                gallary.Name = galaryCreate.name;
                gallary.Logo = uniqe;
                gallary.Created_Date = DateTime.Now;
                var userID = userManger.GetUserId(HttpContext.User);
                gallary.User_Id = userID;
                reposatory.Insert(gallary);
                return Redirect("index");
            }
            return View("inseart");

        }
        [Authorize(Roles = $"{Roles.BUYER_ROLE}")]
        public IActionResult edit(Guid id)
        {
            var gallary = reposatory.GetById(id);
            return View(gallary);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = $"{Roles.BUYER_ROLE}")]
        public IActionResult update(Guid id, Gallary gallary)
        {
            if (ModelState.IsValid)
            {
                reposatory.Update(id, gallary);
                return RedirectToAction("index");
            }
            else
            {
                return View("edit");
            }

        }
        [Authorize(Roles = $"{Roles.BUYER_ROLE}")]
        public IActionResult delete(Guid id)
        {
            Gallary gallary = reposatory.GetById(id);
            return View(gallary);
        }
        [Authorize(Roles = $"{Roles.BUYER_ROLE}")]
        public IActionResult confirmdelete(Guid id)
        {
            reposatory.Delete(id);
            return RedirectToAction("index");
        }
        [Authorize(Roles = $"{Roles.BUYER_ROLE}")]

        public IActionResult Dashboard()
        {
            GalaryInfoDTO dto = new GalaryInfoDTO();
            var userID = userManger.GetUserId(HttpContext.User);
            dto.user_id = userID;
            return View(dto);


        }




        public IActionResult mygallary(string id)
        {
            var gallary = filter.filter(id);


            foreach (var item in gallary)
            {
                GalaryInfoDTO dto = new GalaryInfoDTO();
                dto.Id = item.Id;
                dto.Name = item.Name;
                dto.Logo = item.Logo;
                dto.Created_Date = item.Created_Date;
                galaryInfos.Add(dto);
            }
            return View(galaryInfos);


        }



    }
}

Views/Shared/PageNotFound.cshtml
<h1 class='txt-danger fs-4 mt-5'>خطأ 404 هذ الصفحه غير موجوده</h1>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - حرف</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.rtl.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductGallary.styles.css" asp-append-version="true" />
</head>
<body>
     <header class='sticky-top'>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light my-header-bg border-bottom box-shadow mb-3">
            <div class="container">
                 <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> حرف</a>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">الرئيسيه</a>
                        </li>  

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Category" asp-action="Index">الفئات </a>
                        </li>
                        
                        @if(User.Identity.IsAuthenticated&&User.IsInRole(role: Roles.ADMIN_ROLE))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-info" asp-area="" asp-controller="Category" asp-action="Index">الفئات</a>
                            </li>
                        }
                         <li class="nav-item">
                            <a class="nav-link text-info" asp-area="" asp-controller="Gallary" asp-action="index">المعارض</a>

                        </li>
                                                <li class="nav-item">
                            <a class="nav-link text-info" asp-area="" asp-controller="Product" asp-action="Index">المنتجات</a>
                        </li>
                    
                        
                        <li class="nav-item">
                            <a class="nav-link text-info" asp-area="" asp-controller="Cart" asp-action="Index" >سلة المشتريات </a>
                        </li>
                        
                        <li>
                               @if (User.Identity.IsAuthenticated && User.IsInRole(role: Roles.BUYER_ROLE))
                               {
                                   <a class="nav-link" asp-area="" asp-controller="Gallary" asp-action="Dashboard" asp-route-id="">لوحة النحكم</a>

                               }
                        </li>
                       
                              @* @if (User.Identity.IsAuthenticated && User.IsInRole(role: Roles.BUYER_ROLE))
                               {
                                   <a class="nav-link text-info" asp-area="" asp-controller="Product" asp-action="modifyproducts" asp-route-id="">تعديل المنتجات </a>

                               }*@
                        
                    </ul>

                     <ul class="navbar-nav ms-auto ">
                         @if(!User.Identity.IsAuthenticated){
                            <li class="nav-item m-2">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Register">انشاء حساب</a>
                            </li>
                            <li class="nav-item m-2">
                                <a class="btn btn-outline-info" asp-area="" asp-controller="Account" asp-action="LogIn">تسجيل الدخول</a>
                            </li>
                         }
                         else{
                             <li class="nav-item m-2">
                                <a class="btn btn-outline-danger" asp-area="" asp-controller="Account" asp-action="SignOut">تسجيل الخروج</a>
                            </li>
                                if (User.IsInRole(role: Roles.ADMIN_ROLE)) // check if user is admin to add new admins
                                {
                                    <li class="nav-item m-2">
                                        <a class="btn btn-outline-info" asp-area="" asp-controller="Account" asp-action="AdminRegister">اضافه مشرفين</a>
                                    </li>
                                }
                         }
                    </ul>
                    @if(User.Identity.IsAuthenticated)
                    {
                        <h2 class='text-warning m-3 user-name' >@(User.Identity.Name.ToUpper())</h2>
                    }
                </div>
            </div>
        </nav>
    </header>
  
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProductGallary - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>موقع حرف </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" />

        @*<link rel="stylesheet" href="~/css/font-awesome.min.css"/>*@

        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/css/styles.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/ProductGallary.styles.css" asp-append-version="true" />
       <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </head>
    <body id="page-top">
        
      
        <!--partial view to navbar-->
        
        <partial name="_navbarpartial"/>     

         @await RenderSectionAsync("header", required: false)
        
        <!-- Masthead-->
        <div class="container " style="margin-top:100px">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        
       
        <footer class="border-top footer text-muted py-4">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-start">Copyright &copy; ITI Team 2022</div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                    <div class="col-lg-4 text-lg-end">
                        <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                        <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
                    </div>
                </div>
            </div>
        </footer>
  
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
       
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

Views/Shared/_navbarpartial.cshtml
<!-- Navigation--> 

<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav" style='background-color:#212529'>
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index"> حرف</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars ms-1"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link"  asp-controller="Home" asp-action="Index">الرئيسيه</a></li>
                    <li class="nav-item"><a class="nav-link" href="/Category/Index">الفئات</a></li>
                    <li class="nav-item"><a class="nav-link" href="/Gallary/Index">المعارض</a></li>
                    <li class="nav-item"><a class="nav-link" href="/Product/Index">المنتجات <i class='fa fa-product-hunt'></i></a></li>
               
                     <li class="nav-item">
                               @if (User.Identity.IsAuthenticated && User.IsInRole(role: Roles.ADMIN_ROLE))
                               {
                                   <a class="nav-link" asp-area="" asp-controller="Bill" asp-action="DisplayAllBills" asp-route-id="">الفواتير</a>

                               }
                     </li>
                    @if (User.Identity.IsAuthenticated && User.IsInRole(role: Roles.CUSTOMER_ROLE))
                    {
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Cart" asp-action="Index" >سلة المشتريات <i class='fa fa-shopping-cart'></i> </a></li>
                    }
               
                    @if (User.Identity.IsAuthenticated && User.IsInRole(role: Roles.BUYER_ROLE))
                               {
                         <li class="nav-item">          
                              <a class="nav-link" asp-area="" asp-controller="Gallary" asp-action="Dashboard" asp-route-id="">لوحة التحكم</a>
                         </li>
                     }
                     <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Developers" asp-action="Index" >المطورين</a></li>

                </ul>
               
                
                <ul class="navbar-nav me-auto order-0 ">
                        @if(!User.Identity.IsAuthenticated){
                        <li class="nav-item me-1">
                            <a class="btn btn-outline-primary" asp-area="" asp-controller="Account" asp-action="Register">انشاء حساب</a>
                        </li>
                        <li class="nav-item me-1">
                            <a class="btn btn-outline-primary" asp-area="" asp-controller="Account" asp-action="LogIn">تسجيل الدخول</a>
                        </li>
                        }else{
                            <li class="nav-item me-1">
                            <a class="btn btn-outline-danger" asp-area="" asp-controller="Account" asp-action="SignOut">تسجيل الخروج</a>
                            </li>
                            if (User.IsInRole(role: Roles.ADMIN_ROLE)) // check if user is admin to add new admins
                            {
                                <li class="nav-item me-1">
                                    <a class="btn btn-outline-primary" asp-area="" asp-controller="Account" asp-action="AdminRegister">اضافه مشرفين</a>
                                </li>
                            }


                        }
                </ul>
                 @if(User.Identity.IsAuthenticated)
                    {
                        <h2 class='text-warning m-3 user-name' >@(User.Identity.Name.ToUpper())</h2>
                    }

            </div>
        </div>
 </nav>